<a href="https://colab.research.google.com/github/lucas-vinij/desenvolvedor_python_igti/blob/main/mod02_aula01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 01 - Modulo 2 
Criação de Arrays 

In [1]:
import numpy as np

In [2]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [3]:
# criacao de um array 1D: [1,2,3]
l = [1,2,3]
x = np.array(l)
print("x:",x)
print("shape:", x.shape)

x: [1 2 3]
shape: (3,)


In [8]:
# criacao de um array 2d: listas aninhadas 
l = [[1,2],[3,4]]
x = np.array(l, dtype=int)
print("x:\n",x)
print("shape:",x.shape)

x:
 [[1 2]
 [3 4]]
shape: (2, 2)


In [7]:
# array contendo apenas 0's
dim = (2,2) # (linhas, colunas)
x = np.zeros(dim)
print('x:\n',x)
print(f'shape:{x.shape}')

x:
 [[0. 0.]
 [0. 0.]]
shape:(2, 2)


In [9]:
# array contendo apenas 1's 
size = (2,2) # (linhas, colunas)
x = np.ones(size)
print(f'x:\n{x}')
print(f'shape:{x.shape}')

x:
[[1. 1.]
 [1. 1.]]
shape:(2, 2)


In [10]:
# criacao de valores dentro de um intervalo
# valores uniformes entre 5 e 15
x_min, x_max = 5,15
x = np.linspace(start=x_min, stop=x_max, num=6)
print(f'x:{x}')
print(f'shape: {x.shape}')

x:[ 5.  7.  9. 11. 13. 15.]
shape: (6,)


In [12]:
# criacao da matriz identidade
n = 4
x = np.eye(n)
print(f'x:\n{x}')
print(f'shape:{x.shape}')

x:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape:(4, 4)


In [14]:
# criacao de valores aleatorios
# np.random.seed(10)
x = np.random.random(size=(2,3))
print(f'x:\n{x}')
print(f'shape:{x.shape}')

x:
[[0.53147305 0.18792723 0.68101839]
 [0.90150238 0.31625903 0.25119736]]
shape:(2, 3)
