<a href="https://colab.research.google.com/github/lucas-vinij/desenvolvedor_python_igti/blob/main/Mod02_Aula03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
x = np.ones((2,2))
y = np.eye(2)

In [4]:
x + y

array([[2., 1.],
       [1., 2.]])

In [5]:
x

array([[1., 1.],
       [1., 1.]])

In [6]:
y

array([[1., 0.],
       [0., 1.]])

In [7]:
x - y

array([[0., 1.],
       [1., 0.]])