<a href="https://colab.research.google.com/github/lucas-vinij/desenvolvedor_python_igti/blob/main/Mod02_aula02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aula 02 | Modulo 2

In [1]:
import numpy as np

In [7]:
# selecionar unico valor
# x[linha, coluna] 

In [8]:
# slice 
# x[1:3]
# x[1:3, 1:4] = (linhas 1:3, colunas 1:4)

In [9]:
x = np.linspace(start=10, stop=100, num=10)
print(f'x:{x}')
print(f'shape:{x.shape}')

x:[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
shape:(10,)


In [13]:
x[0]
x[1]
x[9]
x[-1]
x[-2]

90.0

In [17]:
x[0:2]
x[:2]
x[-2:]

array([ 90., 100.])

In [18]:
# slicing em arrays 2d (matrizes)
x = x.reshape(2,5) # reshape de x para 2 linhas e 5 colunas
x

array([[ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.]])

In [25]:
x[0,1]
x[1,-2]
x[1,4]
x[-1,-1]


100.0

In [31]:
x[0, :]
x[0, 1:4]
x[:, [-1]]
x[:, -1]


array([ 50., 100.])

In [35]:
# atencao com compartilhamento de memoria em subarrays
x = np.array([1,2,3])
print(x)
y = x[:2]
y[0] = -100 # alteracao do valor em y altera o valor de x
print(x)


[1 2 3]
[-100    2    3]


In [36]:
x = np.array([1,2,3])
print(x)
y = x[:2].copy()
y[0] = -100
print(x)

[1 2 3]
[1 2 3]
